"""добавил полу img_url в PerevalImages

Revision ID: 1b617b67a3db
Revises: 74c9c5e21ec8
Create Date: 2025-02-10 11:56:50.236340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b617b67a3db'
down_revision: Union[str, None] = '74c9c5e21ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pereval_images', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pereval_images', 'img_url')
    # ### end Alembic commands ###
