"""Изменены связи таблиц PerevalLevel and PerevalAdded

Revision ID: 74c9c5e21ec8
Revises: 95042998aa7d
Create Date: 2025-02-10 11:18:32.941752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c9c5e21ec8'
down_revision: Union[str, None] = '95042998aa7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pereval_added', sa.Column('level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pereval_added', 'pereval_levels', ['level_id'], ['id'])
    op.drop_constraint('pereval_levels_pereval_id_fkey', 'pereval_levels', type_='foreignkey')
    op.drop_column('pereval_levels', 'pereval_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pereval_levels', sa.Column('pereval_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pereval_levels_pereval_id_fkey', 'pereval_levels', 'pereval_added', ['pereval_id'], ['id'])
    op.drop_constraint(None, 'pereval_added', type_='foreignkey')
    op.drop_column('pereval_added', 'level_id')
    # ### end Alembic commands ###
