"""add_connect_user

Revision ID: d1ed9a994d06
Revises: f341706e09fd
Create Date: 2025-02-15 12:56:59.009181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ed9a994d06'
down_revision: Union[str, None] = 'f341706e09fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pereval_added', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pereval_added', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pereval_added', type_='foreignkey')
    op.drop_column('pereval_added', 'user_id')
    # ### end Alembic commands ###
