"""Initial migration

Revision ID: e29c1cb68853
Revises: 
Create Date: 2025-02-08 22:23:36.901688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e29c1cb68853'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coords_id'), 'coords', ['id'], unique=False)
    op.create_table('pereval_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_parent', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pereval_areas_id'), 'pereval_areas', ['id'], unique=False)
    op.create_table('spr_activities_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spr_activities_types_id'), 'spr_activities_types', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('pereval_added',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.TIMESTAMP(), nullable=True),
    sa.Column('beautyTitle', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('other_titles', sa.Text(), nullable=True),
    sa.Column('connect', sa.Text(), nullable=True),
    sa.Column('add_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', postgresql.ENUM('new', 'pending', 'accepted', 'rejected', name='statusnum'), nullable=True),
    sa.Column('coord_id', sa.Integer(), nullable=True),
    sa.Column('level_winter', sa.Text(), nullable=True),
    sa.Column('level_summer', sa.Text(), nullable=True),
    sa.Column('level_autumn', sa.Text(), nullable=True),
    sa.Column('level_spring', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['coord_id'], ['coords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pereval_added_id'), 'pereval_added', ['id'], unique=False)
    op.create_table('pereval_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.TIMESTAMP(), nullable=True),
    sa.Column('img', sa.LargeBinary(), nullable=False),
    sa.Column('pereval_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pereval_id'], ['pereval_added.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pereval_images_id'), 'pereval_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pereval_images_id'), table_name='pereval_images')
    op.drop_table('pereval_images')
    op.drop_index(op.f('ix_pereval_added_id'), table_name='pereval_added')
    op.drop_table('pereval_added')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_spr_activities_types_id'), table_name='spr_activities_types')
    op.drop_table('spr_activities_types')
    op.drop_index(op.f('ix_pereval_areas_id'), table_name='pereval_areas')
    op.drop_table('pereval_areas')
    op.drop_index(op.f('ix_coords_id'), table_name='coords')
    op.drop_table('coords')
    # ### end Alembic commands ###
