"""Initial migration

Revision ID: e8921e0ab629
Revises: e29c1cb68853
Create Date: 2025-02-09 12:16:40.040527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8921e0ab629'
down_revision: Union[str, None] = 'e29c1cb68853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fam', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otc', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'phone')
    op.drop_column('users', 'otc')
    op.drop_column('users', 'fam')
    # ### end Alembic commands ###
