"""Удалил  поле img_url в PerevalImages

Revision ID: f341706e09fd
Revises: 1b617b67a3db
Create Date: 2025-02-10 12:01:25.706613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f341706e09fd'
down_revision: Union[str, None] = '1b617b67a3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pereval_images', 'img',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_column('pereval_images', 'img_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pereval_images', sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('pereval_images', 'img',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    # ### end Alembic commands ###
